"""
LLM-derived features using OpenAI gpt-5-nano (Group E).

Features are cached to cache/llm_features.json keyed by PR number.
At training time, features are pre-computed in batches using a thread pool.
At inference time, the cache is checked first; OpenAI is called on a miss.

Cost tracking:
  gpt-5-nano pricing (per 1M tokens):
    input:        $0.05   → $0.00005  per 1K
    cached input: $0.005  → $0.000005 per 1K
    output:       $0.40   → $0.0004   per 1K

  Override via env vars: GPT5_NANO_INPUT_COST_PER_1K, GPT5_NANO_CACHED_COST_PER_1K,
  GPT5_NANO_OUTPUT_COST_PER_1K.

  Budget is enforced via the budget_usd parameter to precompute_llm_features().
"""

import json
import os
import sys
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import env  # loads .env before os.environ is read below

CACHE_PATH = Path(__file__).parent.parent / "cache" / "llm_features.json"

# gpt-5-nano pricing — $0.05/$0.005/$0.40 per 1M input/cached/output tokens
INPUT_COST_PER_1K  = float(os.environ.get("GPT5_NANO_INPUT_COST_PER_1K",  "0.00005"))
CACHED_COST_PER_1K = float(os.environ.get("GPT5_NANO_CACHED_COST_PER_1K", "0.000005"))
OUTPUT_COST_PER_1K = float(os.environ.get("GPT5_NANO_OUTPUT_COST_PER_1K", "0.0004"))

SAVE_INTERVAL = 20   # persist cache every N completed calls
MAX_WORKERS   = 50   # concurrent OpenAI requests

QUESTIONS_PATH = Path(__file__).parent.parent / "cache" / "llm_questions.json"

# Fallback questions used when discover_questions.py has not been run yet.
# Run `python src/discover_questions.py` first for data-driven questions.
FALLBACK_QUESTIONS = [
    {"id": "q_pr_type",    "question": "What type of change is this? (bugfix/feature/docs/refactor/test/chore/other)", "type": "choice"},
    {"id": "q_title_qual", "question": "How clear and descriptive is the PR title?",  "type": "score"},
    {"id": "q_body_qual",  "question": "How thorough and useful is the PR description?", "type": "score"},
    {"id": "q_is_bot",     "question": "Was this PR generated by a bot or automation?", "type": "bool"},
    {"id": "q_problem",    "question": "Does the PR clearly explain the problem it solves?", "type": "bool"},
]

PR_TYPE_MAP = {
    "bugfix": 0, "feature": 1, "docs": 2, "refactor": 3,
    "test": 4, "chore": 5, "other": 6,
}


def load_questions() -> list[dict]:
    """Load discovered questions from cache, falling back to hardcoded defaults."""
    if QUESTIONS_PATH.exists():
        with open(QUESTIONS_PATH) as f:
            data = json.load(f)
        return data["questions"]
    return FALLBACK_QUESTIONS


def _build_prompts(questions: list[dict]) -> tuple[str, str]:
    """Build system prompt and user template from a questions list."""
    schema_lines = []
    for q in questions:
        qid = q["id"]
        qtype = q["type"]
        if qtype == "bool":
            schema_lines.append(f'  "{qid}": true or false  // {q["question"]}')
        elif qtype == "score":
            schema_lines.append(f'  "{qid}": integer 1-5   // {q["question"]}')
        elif qtype == "choice":
            schema_lines.append(f'  "{qid}": string        // {q["question"]}')
        else:
            schema_lines.append(f'  "{qid}": value         // {q["question"]}')

    schema_str = "{" + ", ".join(
        f'"{q["id"]}": ' + ("true|false" if q["type"] == "bool" else "1-5")
        for q in questions
    ) + "}"
    questions_list = "\n".join(
        f'{q["id"]}: ({q["type"]}) {q["question"]}'
        for q in questions
    )
    system = (
        "You answer questions about GitHub pull requests.\n"
        "Output a single compact JSON object on one line. No prose, no markdown.\n"
        f"Questions:\n{questions_list}\n\n"
        f"Output format (one line): {schema_str}"
    )
    user_template = (
        "PR title: {title}\n\n"
        "PR body:\n{body}"
    )
    return system, user_template


class BudgetExceededError(Exception):
    pass


def _load_cache() -> dict:
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    if CACHE_PATH.exists():
        with open(CACHE_PATH) as f:
            return json.load(f)
    return {}


def _save_cache(cache: dict) -> None:
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = CACHE_PATH.with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(cache, f)
    tmp.replace(CACHE_PATH)  # atomic rename


def _get_client():
    """Return a module-level shared OpenAI client with a pool sized for MAX_WORKERS."""
    if not hasattr(_get_client, "_client"):
        import httpx
        from openai import OpenAI
        _get_client._client = OpenAI(
            http_client=httpx.Client(
                limits=httpx.Limits(
                    max_connections=MAX_WORKERS + 10,
                    max_keepalive_connections=MAX_WORKERS,
                )
            )
        )
    return _get_client._client


def _call_openai(
    title: str, body: str, system_prompt: str, user_template: str
) -> tuple[dict | None, int, int, int]:
    """
    Call OpenAI and return (result, input_tokens, cached_tokens, output_tokens).
    cached_tokens is the subset of input_tokens served from OpenAI's prompt cache.
    Returns (None, 0, 0, 0) on failure.
    """
    try:
        client = _get_client()
        user_msg = user_template.format(
            title=title[:500],
            body=(body or "")[:2000],
        )
        response = client.chat.completions.create(
            model="gpt-5-nano",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_msg},
            ],
            max_completion_tokens=8000,
        )
        choice = response.choices[0]
        raw = choice.message.content or ""

        if not raw.strip():
            # Log enough detail to diagnose on the first empty response
            finish = choice.finish_reason
            refusal = getattr(choice.message, "refusal", None)
            print(f"  [llm_features] Empty content: finish_reason={finish!r} "
                  f"refusal={refusal!r}", file=sys.stderr)
            return None, 0, 0, 0

        # Strip markdown fences if model wraps output despite instructions
        text = raw.strip()
        if text.startswith("```"):
            text = "\n".join(text.split("\n")[1:]).rstrip("`").strip()

        usage = response.usage
        in_tok     = usage.prompt_tokens     if usage else 0
        out_tok    = usage.completion_tokens if usage else 0
        cached_tok = 0
        if usage and hasattr(usage, "prompt_tokens_details") and usage.prompt_tokens_details:
            cached_tok = getattr(usage.prompt_tokens_details, "cached_tokens", 0) or 0
        return json.loads(text), in_tok, cached_tok, out_tok
    except Exception as e:
        print(f"  [llm_features] OpenAI call failed: {e}", file=sys.stderr)
        return None, 0, 0, 0


def _parse_result(raw: dict | None, questions: list[dict]) -> dict:
    """Convert raw OpenAI JSON to numeric features keyed as llm_<question_id>."""
    nan = float("nan")
    if raw is None:
        return {f"llm_{q['id']}": nan for q in questions}

    result = {}
    for q in questions:
        qid = q["id"]
        val = raw.get(qid)
        feat_key = f"llm_{qid}"
        if val is None:
            result[feat_key] = nan
        elif q["type"] == "bool":
            result[feat_key] = float(bool(val))
        elif q["type"] == "score":
            result[feat_key] = float(val)
        elif q["type"] == "choice":
            # Map known choice fields; for unknown types just hash to int
            if qid == "q_pr_type":
                result[feat_key] = float(PR_TYPE_MAP.get(str(val).lower(), PR_TYPE_MAP["other"]))
            else:
                result[feat_key] = float(hash(str(val)) % 100)
        else:
            result[feat_key] = float(val) if isinstance(val, (int, float)) else nan
    return result


def get_llm_features(pr: dict, cache: dict | None = None) -> dict:
    """
    Get LLM features for a single PR. Checks cache first; calls OpenAI on miss.
    For single inference calls — not threaded.
    """
    questions = load_questions()
    system_prompt, user_template = _build_prompts(questions)

    key = str(pr["number"])
    if cache is None:
        cache = _load_cache()

    if key in cache:
        return _parse_result(cache[key], questions)

    raw, _, _, _ = _call_openai(pr.get("title", ""), pr.get("body", ""),
                                system_prompt, user_template)
    cache[key] = raw
    _save_cache(cache)
    return _parse_result(raw, questions)


def precompute_llm_features(
    prs: list[dict],
    verbose: bool = True,
    budget_usd: float = 10.0,
) -> dict:
    """
    Pre-compute LLM features for a batch of PRs using a thread pool.

    - Skips PRs already in cache.
    - Saves cache every SAVE_INTERVAL completions and on exit.
    - Tracks token costs; raises BudgetExceededError (after saving) if budget exceeded.

    Returns:
        Dict mapping pr_number (int) -> feature dict.
    """
    questions = load_questions()
    system_prompt, user_template = _build_prompts(questions)

    cache = _load_cache()
    missing = [pr for pr in prs if str(pr["number"]) not in cache]

    if verbose:
        print(f"[llm_features] Using {len(questions)} questions "
              f"({'discovered' if QUESTIONS_PATH.exists() else 'fallback'})")
        print(f"[llm_features] Cache hits: {len(prs) - len(missing)}/{len(prs)}")
        if missing:
            print(f"[llm_features] Calling OpenAI for {len(missing)} PRs "
                  f"(workers={MAX_WORKERS}, save_every={SAVE_INTERVAL})...")
        print(f"[llm_features] Budget: ${budget_usd:.2f} | "
              f"Pricing: ${INPUT_COST_PER_1K}/1k input, ${OUTPUT_COST_PER_1K}/1k output")

    if not missing:
        return {pr["number"]: _parse_result(cache.get(str(pr["number"])), questions) for pr in prs}

    cache_lock   = threading.Lock()
    cost_lock    = threading.Lock()
    total_cost   = 0.0
    completed    = 0
    budget_hit   = threading.Event()

    def process_pr(pr: dict):
        nonlocal total_cost, completed

        if budget_hit.is_set():
            return pr["number"], None, 0, 0, 0

        raw, in_tok, cached_tok, out_tok = _call_openai(
            pr.get("title", ""), pr.get("body", ""), system_prompt, user_template
        )
        return pr["number"], raw, in_tok, cached_tok, out_tok

    try:
        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            futures = {executor.submit(process_pr, pr): pr for pr in missing}

            for future in as_completed(futures):
                pr_number, raw, in_tok, cached_tok, out_tok = future.result()

                # cached tokens are billed at the lower cached rate
                uncached_tok = max(0, in_tok - cached_tok)
                call_cost = (
                    uncached_tok * INPUT_COST_PER_1K
                    + cached_tok * CACHED_COST_PER_1K
                    + out_tok    * OUTPUT_COST_PER_1K
                ) / 1000.0

                with cache_lock:
                    cache[str(pr_number)] = raw
                    completed += 1
                    should_save = (completed % SAVE_INTERVAL == 0)

                with cost_lock:
                    total_cost += call_cost
                    current_cost = total_cost

                if should_save:
                    with cache_lock:
                        _save_cache(cache)
                    if verbose:
                        print(f"  [{completed}/{len(missing)}] "
                              f"cost so far: ${current_cost:.4f} / ${budget_usd:.2f}")

                if current_cost >= budget_usd:
                    budget_hit.set()
                    with cache_lock:
                        _save_cache(cache)
                    if verbose:
                        print(f"\n[llm_features] Budget ${budget_usd:.2f} exceeded "
                              f"(spent ${current_cost:.4f}). Progress saved.")
                    raise BudgetExceededError(
                        f"LLM budget exceeded: spent ${current_cost:.4f} of ${budget_usd:.2f}. "
                        f"Completed {completed}/{len(missing)} new PRs. "
                        f"Re-run to continue from checkpoint."
                    )

    finally:
        with cache_lock:
            _save_cache(cache)
        if verbose and completed > 0:
            with cost_lock:
                final_cost = total_cost
            hits = len(prs) - len(missing)
            print(f"[llm_features] Finished {completed}/{len(missing)} new calls. "
                  f"Total cost: ${final_cost:.4f}. Cache saved to {CACHE_PATH}")

    return {pr["number"]: _parse_result(cache.get(str(pr["number"])), questions) for pr in prs}
